#!/bin/bash

dotfiles=(
    .alacritty.toml
    .bash_functions
    .bashrc
    .gitconfig
    .gitignore_global
    .guile
    .inputrc
    .pystartup
    .telnetrc
    .tmux.conf
    .Xresources
)

cd

for df in ${dotfiles[@]}; do
    [ -f $df ] && rm -f $df
    ln -s .dotfiles/$df .
done

mkdir -p .config
cd .config
ln -s ~/.dotfiles/nvim nvim
